### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by yishenggudou** [luoye-fe/goh5#1]
hi
请教下 你这个布局部分是怎么实现的

**Comment by luoye-fe** [comment]
@yishenggudou 直接flex实现的，自己的项目，没有考虑那么多的兼容性问题

**Comment by yishenggudou** [comment]
@luoye-fe  编辑, 拖拽布局,以及布局配置化,  我之前有想法做一个其他方面的类似的 感觉还是太复杂了

**Comment by luoye-fe** [comment]
@yishenggudou 编辑的时候所有元素布局都是相对于手机框的呀，然后绝对定位的，布局配置化是指？

**Comment by zzm1988** [comment]
@luoye-fe
元素的定位是使用了绝对定位，在不同的分辨率下不准确，这个要怎么去调整。给个思路。

**Comment by luoye-fe** [comment]
@zzm1988 
在  goh5 里，做了 meta 缩放，所有的定位和大小可以直接使用原尺寸（640_1136）的像素来，在不同分辨率下整个文档会缩放到 640_1136 大小。
