### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by PiGe26** [luoye-fe/goh5#11]
启动node app.js --env==dev 提示找不到config.js模块

**Comment by luoye-fe** [comment]
需要一份数据库配置文件。

[文档](https://github.com/luoye-fe/goh5#%E6%8B%B7%E8%B4%9D%E6%95%B0%E6%8D%AE%E5%BA%93%E9%85%8D%E7%BD%AE)

**Comment by luoye-fe** [comment]
ping ?

**Comment by luoye-fe** [comment]
时间太长，关闭。
