### ISSUE TITLE
mongodb的安装和使用中遇到问题

### ISSUE THREAD

**Issue by zuoliang0** [luoye-fe/goh5#4]
在windows7环境下安装最新3.2版本mongodb。
在起bin目录下执行
<img src='http://i1.buimg.com/1566/f2330a35984d98f8.png'>

> mongodb.exe --dbpath d:/data/db

提示找不程序
<img src='http://i1.buimg.com/1566/71e8753a0a23a461.png'>
请问是版本问题吗？最新版如何操作谢谢

**Comment by luoye-fe** [comment]
`mongod.exe`

不是 `mongodb.exe`。

推荐使用 mongdo v3.0 。

**Comment by zuoliang0** [comment]
怪我咯，如果你有空，可以修改下mongodb.md，谢谢

**Comment by luoye-fe** [comment]
嗯～修改了
