### ISSUE TITLE
我调试通了，感觉好多bug ,瑕不掩瑜，学习学习

### ISSUE THREAD

**Issue by huchao007** [luoye-fe/goh5#5]

**Comment by luoye-fe** [comment]
嗯 = = 并不是很完整，毕竟一个多星期的兴奋期做出来的东西，有很多细节没考虑到。

技术栈跟现在流行的比也有点老了，其实这个项目最重要的还是那些数据结构，编辑和预览共用一套，那个价值比较高。具体的实现并不是最重要的。

加油啦，感谢对本项目的关注。
