### ISSUE TITLE
vue-devtool无法使用

### ISSUE THREAD

**Issue by ppboyly** [luoye-fe/goh5#7]
使用生产模式打包，但是用chrome调试时，vue-devtool显示Devtools inspection is not available because it's in production mode or explicitly disabled by the author. 请问怎么设置可以使用vue-devtool

**Comment by luoye-fe** [comment]
`Vue.config.devtools = true` ？

生产模式为何还要打开 dev-tools 呢

**Comment by ppboyly** [comment]
刚刚接触vue，才知道chrome下有个vue dev-tool   所以想看一看
