### ISSUE TITLE
utils.attachmentSizeFormat 函数bug

### ISSUE THREAD

**Issue by semonpic** [luoye-fe/goh5#8]
utils.attachmentSizeFormat = function(fileSize, level){
    var unit = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    if (fileSize < 1024) {
        return fileSize.toFixed(2) + unit[level];
    } else {
        return utils.attachmentSizeFormat(fileSize / 1024, ++level);
    }
}
当首次调用这个函数时，参数 fileSize<1024  报fileSize.toFixed未定义
此时fileSize还是字符串类型，哈哈  函数开头加上fileSize=fileSize*1

**Comment by luoye-fe** [comment]
😂 当初的练手项目，小瑕疵不少，感谢提 issue
