### ISSUE TITLE
这个前端的swiper有点怪啊

### ISSUE THREAD

**Issue by weituotian** [luoye-fe/goh5#9]
官网最新版没有onslidechangeend 事件，
然后本仓库的swiper的版本有点低。。。
然后这是什么情况？(为什么会发生这种情况)

**Comment by luoye-fe** [comment]
`https://github.com/luoye-fe/goh5/blob/afcaefaf05692fe618b7a017fa08a2521669788f/Front_Stage/src/js/swiper.js`

用的 3.3.1 版本，做了一些特殊定制，拿过来直接放在仓库里了

**Comment by weituotian** [comment]
@luoye-fe 
哦，原来是自己定制的。
如果可以增加易企秀的翻页效果就好了，swiper的翻页效果和易企秀还是不同的。
